### ISSUE TITLE
Load model missing attribute

### ISSUE THREAD

**Issue by rowedenny** [Xtra-Computing/thundersvm#135]
I saved the well-trained models, and then load the model again to read its attributes, but those attributes are missing.

I have checked the thundersvmScikit.py, it seems that attributes including:
support_vectors_, n_support_, dual_coef_ , coef_, intercept_ are all NOT saved.

e.g 
from thundersvmScikit import *
from sklearn.datasets import *

x,y = load_svmlight_file("../dataset/test_dataset.txt")
clf = SVC(verbose=True, gamma=0.5, C=100)
clf.fit(x,y)
clf.save_to_file('./model')

clf = SVC()
clf.load_from_file('./model')
clf.n_support_

**_Traceback (most recent call last):
AttributeError: 'SVC' object has no attribute 'n_support_'_**

P.S the svm(s) in scikit-learn save those parameters, so keeping a consistency would be much appreciated.

**Comment by GODqinbin** [comment]
Hi @rowedenny ,

We have added the attribute support_vectors_, n_support_, dual_coef_ , and intercept_. We will add the attribute coef_ in the future. Thanks.

**Comment by rowedenny** [comment]
Hi @GODqinbin ,thank you for the quick follow-up.

I have tested, it works on SVC, yet not work on OneClassSVM.
Basically, when I save the well-trained model of OneClassSVM and then load it again, python fails.
 
The error reports as follows,
new.load_from_file('./model')
**Segmentation fault (core dumped)**

Would you please check it and fix this?

**Comment by GODqinbin** [comment]
Hi @rowedenny ,

We tried OneClassSVM and it works fine. Can you share the dataset and the command? Then we can reproduce the problem.

**Comment by tuomastik** [comment]
@zeyiwen @GODqinbin When the Python interface was updated in commit af515fac82c0a9e6df692caad865ee78fab84da6, it seems that the `thundersvmScikit.py` related code introduced in the commit 27d3707b4fcce59abd5eccf1af6bc42ec94e573b was deleted. Was that an accident?

**Comment by GODqinbin** [comment]
Hi, @tuomastik 

We have reorganized the structure and moved the file thundersvmScikit.py to "python/thundersvm/thundersvm.py". Now you can use the interface by "import thundersvm".

**Comment by tuomastik** [comment]
@GODqinbin The issue is that when @zeyiwen renamed the file from `thundersvmScikit.py` to `thundersvm.py` he also removed the code that you wrote in commit 27d3707b4fcce59abd5eccf1af6bc42ec94e573b, perhaps by accidentally copying the code from an older version. That can be confirmed by comparing the old and new `load_from_file()` implementation:

* After your bugfix (April 15th 2019): https://github.com/Xtra-Computing/thundersvm/blob/27d3707b4fcce59abd5eccf1af6bc42ec94e573b/python/thundersvmScikit.py#L396:L457
* After reorganizing Python module (April 24th 2019): https://github.com/Xtra-Computing/thundersvm/blob/af515fac82c0a9e6df692caad865ee78fab84da6/python/thundersvm/thundersvm.py#L402:L421

**Comment by GODqinbin** [comment]
Hi, @tuomastik 

Thanks for you feedback! It was an accident... We have updated the file thundersvm.py and it should support the attributes now.

**Comment by tuomastik** [comment]
Thank you for the fast reply and fix @GODqinbin and the whole Xtra Computing Group! :pray: I'm happy to help. It was very difficult to notice the error because the change was done at the same time when the file was renamed, which is why GitHub doesn't show the difference between the old and new file.

**Comment by zeyiwen** [comment]
This should be fixed now.
